# Site settings
title: Edify Education Design
email: kristen@edifyedu.com
description: > # this means to ignore newlines until "baseurl:"
  We think education should make sense. That's why it's all we do. We help people create real learning experiences that other people actually enjoy – and learn from.
baseurl: /edifyedu.com
url: "http://edifyedu.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Author details
kristen_gallagher:
    name: Kristen Gallagher
    email: kristen@edifyedu.com
    web: https://edifyedu.com/about

# Build settings
markdown: kramdown
