# Site settings
title: Edify Education Design
email: kristen@edifyedu.com
description: > # this means to ignore newlines until "baseurl:"
  We think education should make sense. That's why it's all we do. We help people create real learning experiences that other people actually enjoy – and learn from.
baseurl:
url: "http://edifyedu.com" # the base hostname & protocol for your site


# Author details
authors:
  kristen_gallagher:
    name: Kristen Gallagher
    email: kristen@edifyedu.com
    web: https://edifyedu.com/about

# Build settings
markdown: kramdown

exclude: ['vendor']

collections:
  whitepapers:
    output: true
    permalink: /whitepapers/:path/
  speaking:
    output: true
    permalink: /speaking/:path/
